### ISSUE TITLE
Producing fragment size histograms for whole genome data

### ISSUE THREAD

**Issue by skanwal** [alkodsi/ctDNAtools#5]
Hello,

Firstly, thanks for this useful resource.

I've been trying to follow some of the examples in the 'Get Started` guide to produce fragment size histogram for my data.

I am currently running it as follows:

```
bfs_SBJ00037 <- bin_fragment_size(bam ="path/to/sample.bam",
          min_size = 1,
          max_size = 400,
          normalized = TRUE,
          bin_size = 10)
```

The bam is 60G in size and I haven't been able to get any results from the use as above. I'm running on a cluster and the job has been running for more than 12hours now. 

I wanted to ask:

- If I am using the program correctly or I need to first run `get_fragment_size` on my bam to produce the histograms?
- What are the expected runtime for the program on whole genome data? I'm currently throwing 64G memory at it.
- Also, are there any recommendations to decide appropriate bin size?

**Comment by alkodsi** [comment]
Hi @skanwal 

Thank you for your feedback. You are using the correct function, but the functions for handling fragment size in this package are not designed with huge whole-genome bam files in mind. I can suggest you two solutions. 

1. You don't need the whole bam file to get an accurate histogram. Few million reads would be  more than enough. So you can downsample your bam file and then run the function (see -s in samtools view)

2. If you do need to use the whole bam, you can analyze the bam in batches by using **target** input having one chromosome at a time (maybe in parallel to make it faster). In this case, set ```normalized = FALSE``` so that you can add the counts for each bin across chromosomes.

Regarding bin size, I think it depends on the application in mind. A bin size of 1 is the highest resolution, so you can try first with 1 and decide then if you want to continue with a fixed larger bin size or a custom bin size.

**Comment by alkodsi** [comment]
Here is an example code to run the analysis in batches by chromosome in parallel:

```
library(ctDNAtools)
library(BSgenome.Hsapiens.UCSC.hg19)
library(furrr)
# set the number of threads to a suitable number
plan(multiprocess, workers = 12)

bamT1 <- system.file("extdata", "T1.bam", package = "ctDNAtools")

targets_split <- seqinfo(BSgenome.Hsapiens.UCSC.hg19) %>% 
       as.data.frame() %>% 
       tibble::rownames_to_column("chr") %>% 
       dplyr::filter(chr %in% paste0("chr",c(1:22, "X", "Y"))) %>%
       mutate(start = 1) %>%
       select(chr, start, end = seqlengths) %>% 
       split(.$chr)

frag_hists <- furrr::future_map(targets_split, ~bin_fragment_size(bamT1, targets = .x))

frag_hists <- frag_hists %>%
         purrr::map2(names(targets_split), ~set_names(.x, c("Breaks", .y))) %>%
         purrr::reduce(dplyr::inner_join, by = "Breaks")

total_histogram <- data.frame(Breaks = frag_hists$Breaks, bamT1 = rowSums(frag_hists[,-1]))
```

**Comment by skanwal** [comment]
Thanks for the quick response.

I've been trying few things trying to get this to work but my jobs have been running into `Job ~ID~ has exceeded memory allocation on node`

I've been trying to run on a single node on our cluster with 16 cores. The maximum memory I had allocated so far is 128GB.

To check, my understanding is `workers` in `plan(multiprocess, workers = 12)` should be equivalent to the cores I am setting the batch run script?
I've also tried limiting to just a couple chromosomes in `targets_split` but still got the same memory issue. I _suspect_ it probably have to do with the function trying to read the full bam file in memory?

I might next try limiting to a single chromosome, which probably won't need the following bit of analysis:

```
frag_hists <- frag_hists %>%
         purrr::map2(names(targets_split), ~set_names(.x, c("Breaks", .y))) %>%
         purrr::reduce(dplyr::inner_join, by = "Breaks")
total_histogram <- data.frame(Breaks = frag_hists$Breaks, bamT1 = rowSums(frag_hists[,-1]))
```

**Comment by alkodsi** [comment]
Yes the workers is basically the number of cores the script will use. But if you were not able to run one chromosome due to memory issue, then I am afraid there is no workaround with the current implementation, and it is not straightforward to implement a chunk size for these functions. You could split one chromosome to smaller parts, but then the reads on the boundaries will be counted twice. 
I would recommend that you downsample the bam file if your goal is to get the distribution because, as I mentioned, it doesn't need the whole bam to get the fragment size histogram accurately.

**Comment by skanwal** [comment]
Thanks for confirming.
I'll report back if I have issues with the downsampled bam file.

Best,
Sehrish
